const iconImports = {
  'acero.png': require('../../assets/icons-png/acero.png'),
  'albaneria.png': require('../../assets/icons-png/albaneria.png'),
  'aparatos-sanitarios.png': require('../../assets/icons-png/aparatos-sanitarios.png'),
  'ascensores.png': require('../../assets/icons-png/ascensores.png'),
  'barandas.png': require('../../assets/icons-png/barandas.png'),
  'carpinteria.png': require('../../assets/icons-png/carpinteria.png'),
  'carpinteria-metalica.png': require('../../assets/icons-png/carpinteria-metalica.png'),
  'casco.png': require('../../assets/icons-png/casco.png'),
  'casco2.png': require('../../assets/icons-png/casco2.png'),
  'checklist.png': require('../../assets/icons-png/checklist.png'),
  'compactacion.png': require('../../assets/icons-png/compactacion.png'),
  'concreto.png': require('../../assets/icons-png/concreto.png'),
  'concreto-armado.png': require('../../assets/icons-png/concreto-armado.png'),
  'concreto-hormigon.png': require('../../assets/icons-png/concreto-hormigon.png'),
  'concreto-simple.png': require('../../assets/icons-png/concreto-simple.png'),
  'cristaleria-y-espejos.png': require('../../assets/icons-png/cristaleria-y-espejos.png'),
  'demolicion.png': require('../../assets/icons-png/demolicion.png'),
  'demolicion2.png': require('../../assets/icons-png/demolicion2.png'),
  'desmontaje.png': require('../../assets/icons-png/desmontaje.png'),
  'encofrado.png': require('../../assets/icons-png/encofrado.png'),
  'estructura-metalica.png': require('../../assets/icons-png/estructura-metalica.png'),
  'instalaciones-a-gas.png': require('../../assets/icons-png/instalaciones-a-gas.png'),
  'instalaciones-electricas.png': require('../../assets/icons-png/instalaciones-electricas.png'),
  'instalaciones-sanitarias.png': require('../../assets/icons-png/instalaciones-sanitarias.png'),
  'montaje-y-desmontaje.png': require('../../assets/icons-png/montaje-y-desmontaje.png'),
  'movimiento-tierra.png': require('../../assets/icons-png/movimiento-tierra.png'),
  'muebleria.png': require('../../assets/icons-png/muebleria.png'),
  'otras-actividades.png': require('../../assets/icons-png/otras-actividades.png'),
  'pastelero.png': require('../../assets/icons-png/pastelero.png'),
  'pavimentos.png': require('../../assets/icons-png/pavimentos.png'),
  'pintura.png': require('../../assets/icons-png/pintura.png'),
  'relleno.png': require('../../assets/icons-png/relleno.png'),
  'reporte.png': require('../../assets/icons-png/reporte.png'),
  'retiro-de-material.png': require('../../assets/icons-png/retiro-de-material.png'),
  'revestimiento.png': require('../../assets/icons-png/revestimiento.png'),
  'sistema-construccion-en-seco.png': require('../../assets/icons-png/sistema-construccion-en-seco.png'),
  'sistema-contra-incendios.png': require('../../assets/icons-png/sistema-contra-incendios.png'),
  'sistema-de-contencion.png': require('../../assets/icons-png/sistema-de-contencion.png'),
  'suministro-materiales.png': require('../../assets/icons-png/suministro-materiales.png'),
  'supervision.png': require('../../assets/icons-png/supervision.png'),
  'telecomunicaciones.png': require('../../assets/icons-png/telecomunicaciones.png'),
  'trabajos-humedos.png': require('../../assets/icons-png/trabajos-humedos.png'),
  'usuario-hombre.png': require('../../assets/icons-png/usuario-hombre.png'),
  'usuario-mujer.png': require('../../assets/icons-png/usuario-mujer.png'),
  'vaciado.png': require('../../assets/icons-png/vaciado.png'),
};

const iconsFiles = [
  "acero.png",
  "albaneria.png",
  "aparatos-sanitarios.png",
  "ascensores.png",
  "barandas.png",
  "carpinteria.png",
  "carpinteria-metalica.png",
  "casco.png",
  "casco2.png",
  "checklist.png",
  "compactacion.png",
  "concreto.png",
  "concreto-armado.png",
  "concreto-hormigon.png",
  "concreto-simple.png",
  "cristaleria-y-espejos.png",
  "demolicion.png",
  "demolicion2.png",
  "desmontaje.png", 
  "encofrado.png",
  "estructura-metalica.png",
  "instalaciones-a-gas.png",
  "instalaciones-electricas.png",
  "instalaciones-sanitarias.png",
  "montaje-y-desmontaje.png",
  "movimiento-tierra.png",
  "muebleria.png",
  "otras-actividades.png",
  "pastelero.png",
  "pavimentos.png",
  "pintura.png",
  "relleno.png",
  "reporte.png",
  "retiro-de-material.png",
  "revestimiento.png",
  "sistema-construccion-en-seco.png",
  "sistema-contra-incendios.png",
  "sistema-de-contencion.png",
  "suministro-materiales.png",
  "supervision.png",
  "telecomunicaciones.png",
  "trabajos-humedos.png",
  "usuario-hombre.png",
  "usuario-mujer.png", 
  "vaciado.png"
];

export { iconImports, iconsFiles };
export default iconImports;