const iconImports = {
  'trabajos-sanitarios.png': require('../../assets/icons-png/trabajos-sanitarios.png'),
  'aceros.png': require('../../assets/icons-png/aceros.png'),
  'albanileria.png': require('../../assets/icons-png/albanileria.png'),
  'alerta.png': require('../../assets/icons-png/alerta.png'),
  'brocha.png': require('../../assets/icons-png/brocha.png'),
  'camara.png': require('../../assets/icons-png/camara.png'),
  'camion-de-suministros.png': require('../../assets/icons-png/camion-de-suministros.png'),
  'camion-mixer.png': require('../../assets/icons-png/camion-mixer.png'),
  'casco.png': require('../../assets/icons-png/casco.png'),
  'charla-ssoma.png': require('../../assets/icons-png/charla-ssoma.png'),
  'compactacion-manual.png': require('../../assets/icons-png/compactacion-manual.png'),
  'compactadora.png': require('../../assets/icons-png/compactadora.png'),
  'concreto.png': require('../../assets/icons-png/concreto.png'),
  'cristaleria.png': require('../../assets/icons-png/cristaleria.png'),
  'enchapes.png': require('../../assets/icons-png/enchapes.png'),
  'encofrado.png': require('../../assets/icons-png/encofrado.png'),
  'entrega-epp.png': require('../../assets/icons-png/entrega-epp.png'),
  'entrega-herramienta.png': require('../../assets/icons-png/entrega-herramienta.png'),
  'escoba.png': require('../../assets/icons-png/escoba.png'),
  'escudo.png': require('../../assets/icons-png/escudo.png'),
  'grua.png': require('../../assets/icons-png/grua.png'),
  'levantamiento-de-obs.png': require('../../assets/icons-png/levantamiento-de-obs.png'),
  'muebles.png': require('../../assets/icons-png/muebles.png'),
  'paisajismo.png': require('../../assets/icons-png/paisajismo.png'),
  'pala.png': require('../../assets/icons-png/pala.png'),
  'piedra-natural.png': require('../../assets/icons-png/piedra-natural.png'),
  'pruebas-concreto.png': require('../../assets/icons-png/pruebas-concreto.png'),
  'pruebas-electricas.png': require('../../assets/icons-png/pruebas-electricas.png'),
  'pruebas-sanitarias.png': require('../../assets/icons-png/pruebas-sanitarias.png'),
  'puerta.png': require('../../assets/icons-png/puerta.png'),
  'reporte.png': require('../../assets/icons-png/reporte.png'),
  'retiro-desmonte.png': require('../../assets/icons-png/retiro-desmonte.png'),
  'retroexcavadora.png': require('../../assets/icons-png/retroexcavadora.png'),
  'reunion.png': require('../../assets/icons-png/reunion.png'),
  'rotomartillo.png': require('../../assets/icons-png/rotomartillo.png'),
  'sci.png': require('../../assets/icons-png/sci.png'),
  'senaleticas.png': require('../../assets/icons-png/senaleticas.png'),
  'tabiqueria-drywall.png': require('../../assets/icons-png/tabiqueria-drywall.png'),
  'trabajos-electricos.png': require('../../assets/icons-png/trabajos-electricos.png'),
  'trabajos-en-caliente.png': require('../../assets/icons-png/trabajos-en-caliente.png'),
  'trabajos-humedos.png': require('../../assets/icons-png/trabajos-humedos.png'),
  'trabajos-mecanicos.png': require('../../assets/icons-png/trabajos-mecanicos.png'),
};

const iconsFiles = [
  'trabajos-sanitarios.png',
  'aceros.png',
  'albanileria.png',
  'alerta.png',
  'brocha.png',
  'camara.png',
  'camion-de-suministros.png',
  'camion-mixer.png',
  'casco.png',
  'charla-ssoma.png',
  'compactacion-manual.png',
  'compactadora.png',
  'concreto.png',
  'cristaleria.png',
  'enchapes.png',
  'encofrado.png',
  'entrega-epp.png',
  'entrega-herramienta.png',
  'escoba.png',
  'escudo.png',
  'grua.png',
  'levantamiento-de-obs.png',
  'muebles.png',
  'paisajismo.png',
  'pala.png',
  'piedra-natural.png',
  'pruebas-concreto.png',
  'pruebas-electricas.png',
  'pruebas-sanitarias.png',
  'puerta.png',
  'reporte.png',
  'retiro-desmonte.png',
  'retroexcavadora.png',
  'reunion.png',
  'rotomartillo.png',
  'sci.png',
  'senaleticas.png',
  'tabiqueria-drywall.png',
  'trabajos-electricos.png',
  'trabajos-en-caliente.png',
  'trabajos-humedos.png',
  'trabajos-mecanicos.png',
];

export { iconImports, iconsFiles };
export default iconImports;